 name: Sixsgames Live Scanner

on:
  workflow_dispatch:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install required libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install websocket-client requests

      - name: Run Sixsgames Scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python test_deriv.py
